// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnagramsPostGame } from "./AnagramsPostGame";
import type { WordBombPostGame } from "./WordBombPostGame";

export type PostGameInfo = { "kind": "wordBomb" } & WordBombPostGame | { "kind": "anagrams" } & AnagramsPostGame;
