// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerAnagrams } from "./ServerAnagrams";
import type { ServerWordBomb } from "./ServerWordBomb";

export type ServerGame = { "kind": "wordBomb", "data": ServerWordBomb } | { "kind": "anagrams", "data": ServerAnagrams } | { "kind": "endRequest", "data": { uuid: string, } };
