// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerAction } from "./TimerAction";

export type ServerLobby = { "kind": "ready", uuid: string, timer: TimerAction, } | { "kind": "unready", uuid: string, timer: TimerAction, } | { "kind": "practice", prompts: Array<string>, } | { "kind": "practiceResult", correct: boolean, };
