// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";
import type { PostGameInfo } from "./PostGameInfo";
import type { RoomSettings } from "./RoomSettings";
import type { ServerClient } from "./ServerClient";
import type { ServerGame } from "./ServerGame";
import type { ServerGeneral } from "./ServerGeneral";
import type { ServerLobby } from "./ServerLobby";
import type { ServerState } from "./ServerState";

export type ServerMessage = { "kind": "info", "data": { 
/**
 * Joined client's designated UUID.
 */
uuid: string, 
/**
 * Room clients.
 */
clients: { [key in string]?: ServerClient }, 
/**
 * Room and game settings.
 */
settings: RoomSettings, 
/**
 * State variant data of the room (lobby | game -> (game kind)).
 */
state: ServerState, } } | { "kind": "join", "data": { uuid: string, client: ServerClient, } } | { "kind": "leave", "data": { uuid: string, newOwner: string | null, } } | { "kind": "gameStart", "data": { 
/**
 * Contains the player's rejoin token. Is `None` if client is spectating.
 */
rejoinToken: string | null, state: GameState, } } | { "kind": "gameEnd", "data": { postGameInfo: PostGameInfo | null, 
/**
 * Is `Some` with a random client's uuid if the previous room owner
 * left during game and hasn't come back.
 */
newOwner: string | null, } } | { "kind": "general", "data": ServerGeneral } | { "kind": "lobby", "data": ServerLobby } | { "kind": "game", "data": ServerGame };
