// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Context } from "./Context";
import type { RoomSettings } from "./RoomSettings";
import type { ServerClient } from "./ServerClient";

export type ServerGeneral = { "kind": "info" } & Context | { "kind": "join", uuid: string, client: ServerClient, } | { "kind": "leave", uuid: string, newOwner: string | null, } | { "kind": "pong", timestamp: bigint, } | { "kind": "chat", author: string, content: string, } | { "kind": "settings" } & RoomSettings | { "kind": "error", message: string, };
