// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WordBombPostGame = { winner: string, minsElapsed: number, wordsUsed: number, fastestGuesses: Array<[string, number]>, longestWords: Array<[string, string]>, avgWpms: Array<[string, number]>, avgWordLengths: Array<[string, number]>, };
