// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientAnagrams } from "./ClientAnagrams";
import type { ClientGame } from "./ClientGame";
import type { ClientGeneral } from "./ClientGeneral";
import type { ClientLobby } from "./ClientLobby";
import type { ClientWordBomb } from "./ClientWordBomb";

export type ClientMessage = { "kind": "general", "data": ClientGeneral } | { "kind": "lobby", "data": ClientLobby } | { "kind": "game", "data": ClientGame } | { "kind": "wordBomb", "data": ClientWordBomb } | { "kind": "anagrams", "data": ClientAnagrams };
