// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSettings } from "./RoomSettings";
import type { ServerClient } from "./ServerClient";
import type { ServerState } from "./ServerState";

export type DetailedRoomInfo = { settings: RoomSettings, clients: Array<ServerClient>, state: ServerState, };
