// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostGameInfo } from "./PostGameInfo";

export type LobbyState = { ready: Array<string>, 
/**
 * Unix timestamp of when the countdown timer started.
 */
timerStart: number | null, prevGame: PostGameInfo | null, };
