// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSettings } from "./RoomSettings";
import type { ServerClient } from "./ServerClient";

export type RoomInfo = { settings: RoomSettings, clients: Array<ServerClient>, };
