// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnagramsSettings } from "./AnagramsSettings";
import type { GameType } from "./GameType";
import type { WordBombSettings } from "./WordBombSettings";

export type RoomSettings = { public: boolean, owner: string, size: number, game: GameType, wordBomb: WordBombSettings, anagrams: AnagramsSettings, };
