// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";
import type { PostGameInfo } from "./PostGameInfo";
import type { ServerClient } from "./ServerClient";

export type ServerCore = { "kind": "join", uuid: string, client: ServerClient, } | { "kind": "leave", uuid: string, newOwner: string | null, } | { "kind": "gameStart", 
/**
 * Contains the player's rejoin token. Is `None` if client is spectating.
 */
rejoinToken: string | null, state: GameState, } | { "kind": "gameEnd", postGameInfo: PostGameInfo | null, 
/**
 * Is `Some` with a random client's uuid if the previous room owner
 * left during game and hasn't come back.
 */
newOwner: string | null, };
