// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";
import type { PostGameInfo } from "./PostGameInfo";
import type { ServerClient } from "./ServerClient";

export type ServerCore = { "kind": "join", uuid: string, client: ServerClient, } | { "kind": "rejoin", uuid: string, } | { "kind": "leave", uuid: string, } | { "kind": "gameStart", state: GameState, } | { "kind": "gameEnd", postGameInfo: PostGameInfo | null, };
