// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerClient = { 
/**
 * Client username.
 */
username: string, 
/**
 * URL to account avatar.
 */
avatarUrl: string | null, 
/**
 * Is client currently connected? (Possibly not in game).
 */
connected: boolean, };
