// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerAnagrams = { "kind": "valid", uuid: string, points: number, } | { "kind": "invalid", 
/**
 * Reason for invalid guess (ex: "guess doesn't include prompt")
 */
reason: string, };
