// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerAnagrams = { "kind": "valid", uuid: string, word: string, points: number, } | { "kind": "invalid", uuid: string, reason: string, };
