// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerWordBomb = { "kind": "input", input: string, } | { "kind": "valid", 
/**
 * Current player's guess that was valid.
 */
guess: string, 
/**
 * True if the current player has used up all letters.
 */
life: boolean, 
/**
 * New prompt.
 */
prompt: string, 
/**
 * Player UUID of new turn.
 */
turn: string, } | { "kind": "invalid", 
/**
 * Reason for invalid guess (ex: "guess doesn't include prompt")
 */
reason: string, } | { "kind": "exploded", 
/**
 * New prompt.
 */
prompt: string, 
/**
 * Player UUID of new turn.
 */
turn: string, };
