// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameState } from "./GameState";
import type { LobbyState } from "./LobbyState";

/**
 * Room variant state sent to clients when they join.
 */
export type ServerState = { "kind": "lobby" } & LobbyState | { "kind": "game" } & GameState;
