// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSettings } from "./RoomSettings";
import type { ServerAnagrams } from "./ServerAnagrams";
import type { ServerClient } from "./ServerClient";
import type { ServerCore } from "./ServerCore";
import type { ServerGame } from "./ServerGame";
import type { ServerGeneral } from "./ServerGeneral";
import type { ServerLobby } from "./ServerLobby";
import type { ServerState } from "./ServerState";
import type { ServerWordBomb } from "./ServerWordBomb";

export type ServerMessage = { "kind": "info", "data": { 
/**
 * Joined client's designated UUID.
 */
uuid: string, 
/**
 * Room clients.
 */
clients: { [key in string]?: ServerClient }, 
/**
 * Room and game settings.
 */
settings: RoomSettings, 
/**
 * State variant data of the room (lobby | game -> (game kind)).
 */
state: ServerState, } } | { "kind": "core", "data": ServerCore } | { "kind": "general", "data": ServerGeneral } | { "kind": "lobby", "data": ServerLobby } | { "kind": "game", "data": ServerGame } | { "kind": "wordBomb", "data": ServerWordBomb } | { "kind": "anagrams", "data": ServerAnagrams };
