// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSettings } from "./RoomSettings";

export type ServerGeneral = { "kind": "pong", timestamp: bigint, } | { "kind": "chat", author: string, content: string, } | { "kind": "settings" } & RoomSettings | { "kind": "error", message: string, };
