// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnagramsPostGame = { originalWord: string, leaderboard: Array<[string, number]>, usedWords: Array<[string, Array<string>]>, totalGuesses: Array<[string, number]>, };
