// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSettings } from "./RoomSettings";

export type ClientLobby = { "kind": "roomSettings" } & RoomSettings | { "kind": "ready" } | { "kind": "startEarly" } | { "kind": "unready" } | { "kind": "practiceRequest" } | { "kind": "practiceSubmission", prompt: string, input: string, };
