// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientWordBomb } from "./ClientWordBomb";

export type ClientInGame = { "kind": "wordBomb", "data": ClientWordBomb } | { "kind": "endRequest" } | { "kind": "forceEnd" };
