// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientGeneral } from "./ClientGeneral";
import type { ClientInGame } from "./ClientInGame";
import type { ClientLobby } from "./ClientLobby";

export type ClientMessage = { "kind": "general", "data": ClientGeneral } | { "kind": "lobby", "data": ClientLobby } | { "kind": "inGame", "data": ClientInGame };
