// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientAnagrams } from "./ClientAnagrams";
import type { ClientWordBomb } from "./ClientWordBomb";

export type ClientGame = { "kind": "wordBomb", "data": ClientWordBomb } | { "kind": "anagrams", "data": ClientAnagrams } | { "kind": "endRequest" } | { "kind": "forceEnd" };
