// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSettings } from "./RoomSettings";

export type ClientGeneral = { "kind": "ping", timestamp: bigint, } | { "kind": "chat", content: string, } | { "kind": "settings" } & RoomSettings;
