// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnagramsPostGameInfo } from "./AnagramsPostGameInfo";
import type { WordBombPostGameInfo } from "./WordBombPostGameInfo";

export type PostGameInfo = { "kind": "wordBomb" } & WordBombPostGameInfo | { "kind": "anagrams" } & AnagramsPostGameInfo;
