// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WordBombSettings } from "./WordBombSettings";

export type RoomSettings = { public: boolean, wordBomb: WordBombSettings, };
