// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSettings } from "./RoomSettings";
import type { ServerClient } from "./ServerClient";
import type { ServerState } from "./ServerState";

export type ServerGeneral = { "kind": "info", 
/**
 * Joined client's designated UUID.
 */
uuid: string, 
/**
 * Room and game settings.
 */
settings: RoomSettings, 
/**
 * Room clients.
 */
clients: { [key in string]?: ServerClient }, 
/**
 * State of the room (lobby | type of game).
 * TODO: Box to reduce variant size?.
 */
state: ServerState, } | { "kind": "join", uuid: string, client: ServerClient, } | { "kind": "leave", uuid: string, new_owner: string | null, } | { "kind": "pong", timestamp: bigint, } | { "kind": "chat", author: string, content: string, } | { "kind": "settings" } & RoomSettings | { "kind": "error", message: string, };
