// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerGeneral = { "kind": "join", uuid: string, } | { "kind": "leave", uuid: string, } | { "kind": "chat", author: string, content: string, } | { "kind": "error", message: string, };
