// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameInfo } from "./GameInfo";

export type ServerGame = { "kind": "gameEndRequest", uuid: string, } | { "kind": "gameEnded", info: GameInfo, 
/**
 * Is `Some` with a random client's uuid if the previous room owner
 * left during game and hasn't come back.
 */
newOwner: string | null, };
