// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomSettings } from "./RoomSettings";
import type { ServerGameState } from "./ServerGameState";
import type { TimerAction } from "./TimerAction";

export type ServerLobby = { "kind": "settings" } & RoomSettings | { "kind": "ready", uuid: string, timer: TimerAction, } | { "kind": "unready", uuid: string, timer: TimerAction, } | { "kind": "practice", prompts: Array<string>, } | { "kind": "practiceResult", correct: boolean, } | { "kind": "gameStarted", 
/**
 * Contains the player's rejoin token. Is `None` if client is spectating.
 */
rejoinToken: string | null, state: ServerGameState, };
