// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerClient = { uuid: string, username: string, 
/**
 * URL to account avatar.
 */
avatarUrl: string | null, 
/**
 * `true` if player disconnected in game only.
 */
disconnected: boolean, };
