// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerGame } from "./ServerGame";
import type { ServerGeneral } from "./ServerGeneral";
import type { ServerLobby } from "./ServerLobby";
import type { ServerWordBomb } from "./ServerWordBomb";
import type { State } from "./State";

export type ServerMessage = { "kind": "info", "data": { 
/**
 * Joined client's designated UUID.
 */
uuid: string, 
/**
 * State of the room (game, settings).
 */
state: State, } } | { "kind": "general", "data": ServerGeneral } | { "kind": "lobby", "data": ServerLobby } | { "kind": "game", "data": ServerGame } | { "kind": "wordBomb", "data": ServerWordBomb };
