// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerLobby = { "kind": "ready", uuid: string, startTimer: boolean | null, } | { "kind": "unready", uuid: string, stopTimer: boolean | null, } | { "kind": "practice", prompts: Array<string>, } | { "kind": "practiceResult" } & boolean;
