// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostGameInfo } from "./PostGameInfo";
import type { ServerAnagrams } from "./ServerAnagrams";
import type { ServerWordBomb } from "./ServerWordBomb";

export type ServerGame = { "kind": "wordBomb" } & ServerWordBomb | { "kind": "anagrams" } & ServerAnagrams | { "kind": "endRequest", uuid: string, } | { "kind": "ended", postGameInfo: PostGameInfo, 
/**
 * Is `Some` with a random client's uuid if the previous room owner
 * left during game and hasn't come back.
 */
newOwner: string | null, };
