// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerGameState } from "./ServerGameState";

/**
 * Room state sent to clients when they join.
 */
export type ServerState = { "kind": "lobby", ready: Array<string>, 
/**
 * Unix timestamp of when the countdown timer started.
 */
timerStart: bigint | null, } | { "kind": "game", state: ServerGameState, 
/**
 * UUIDs of players requesting to end the current game.
 */
requestingEnd: Array<string>, };
