// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerGame } from "./ServerGame";
import type { ServerGeneral } from "./ServerGeneral";
import type { ServerLobby } from "./ServerLobby";

export type ServerMessage = { "kind": "general", "data": ServerGeneral } | { "kind": "lobby", "data": ServerLobby } | { "kind": "game", "data": ServerGame };
