// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WordBombPlayer } from "./WordBombPlayer";

export type WordBombState = { players: Array<WordBombPlayer>, turn: string, prompt: string, };
